version: '3'

services:
  db:
    image: postgres
    volumes:
      - db_data_hackaton:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data_hackaton:
    driver: local